-- Databricks notebook source
SELECT 
DD.DRIVER_NAME,
COUNT(1) AS NUMBER_OF_RACES,
SUM(DD.CALCULATED_POINTS) AS POINTS,
ROUND(AVG(DD.CALCULATED_POINTS),2) AS AVG_POINTS
FROM F1_PRESENTATION.CALCULATED_RACE_RESULT AS DD
GROUP BY DRIVER_NAME
HAVING COUNT(1)>50
ORDER BY AVG_POINTS DESC

-- COMMAND ----------

SELECT 
DD.DRIVER_NAME,
COUNT(1) AS NUMBER_OF_RACES,
SUM(DD.CALCULATED_POINTS) AS POINTS,
ROUND(AVG(DD.CALCULATED_POINTS),2) AS AVG_POINTS
FROM F1_PRESENTATION.CALCULATED_RACE_RESULT AS DD
WHERE DD.YEAR BETWEEN 2011 AND 2022
GROUP BY DRIVER_NAME
HAVING COUNT(1)>50
ORDER BY AVG_POINTS DESC

-- COMMAND ----------

SELECT 
DD.DRIVER_NAME,
COUNT(1) AS NUMBER_OF_RACES,
SUM(DD.CALCULATED_POINTS) AS POINTS,
ROUND(AVG(DD.CALCULATED_POINTS),2) AS AVG_POINTS
FROM F1_PRESENTATION.CALCULATED_RACE_RESULT AS DD
WHERE DD.YEAR BETWEEN 2001 AND 2010
GROUP BY DRIVER_NAME
HAVING COUNT(1)>50
ORDER BY AVG_POINTS DESC

-- COMMAND ----------


