-- Databricks notebook source
-- MAGIC %python
-- MAGIC html="<h1 align='center',>Formula <a style='color:red;''>1</a> Dominant DRIVER OVER THE YEARS</h1>"
-- MAGIC displayHTML(html)

-- COMMAND ----------

CREATE OR REPLACE TEMP VIEW DOMINAT_DRIVERS
AS
SELECT 
      DD.DRIVER_NAME,
      COUNT(1) AS NUMBER_OF_RACES,
      SUM(DD.CALCULATED_POINTS) AS POINTS,
      ROUND(AVG(DD.CALCULATED_POINTS),2) AS AVG_POINTS,
      RANK() OVER(ORDER BY AVG(DD.CALCULATED_POINTS) DESC ) AS RANKING
FROM F1_PRESENTATION.CALCULATED_RACE_RESULT AS DD
GROUP BY DRIVER_NAME
HAVING COUNT(1) > 50
ORDER BY AVG_POINTS DESC

-- COMMAND ----------

SELECT DD.YEAR,
      DD.DRIVER_NAME,
      COUNT(1) AS NUMBER_OF_RACES,
      SUM(DD.CALCULATED_POINTS) AS POINTS,
      ROUND(AVG(DD.CALCULATED_POINTS),2) AS AVG_POINTS
FROM F1_PRESENTATION.CALCULATED_RACE_RESULT AS DD
WHERE DD.DRIVER_NAME IN (SELECT DRIVER_NAME FROM DOMINAT_DRIVERS WHERE RANKING <=10)
GROUP BY DRIVER_NAME,DD.YEAR
ORDER BY DD.YEAR,AVG_POINTS,DD.YEAR DESC

-- COMMAND ----------

SELECT DD.YEAR,
      DD.DRIVER_NAME,
      COUNT(1) AS NUMBER_OF_RACES,
      SUM(DD.CALCULATED_POINTS) AS POINTS,
      ROUND(AVG(DD.CALCULATED_POINTS),2) AS AVG_POINTS
FROM F1_PRESENTATION.CALCULATED_RACE_RESULT AS DD
WHERE DD.DRIVER_NAME IN (SELECT DRIVER_NAME FROM DOMINAT_DRIVERS WHERE RANKING <=10)
GROUP BY DRIVER_NAME,DD.YEAR
ORDER BY DD.YEAR,AVG_POINTS,DD.YEAR DESC

-- COMMAND ----------

SELECT DD.YEAR,
      DD.DRIVER_NAME,
      COUNT(1) AS NUMBER_OF_RACES,
      SUM(DD.CALCULATED_POINTS) AS POINTS,
      ROUND(AVG(DD.CALCULATED_POINTS),2) AS AVG_POINTS
FROM F1_PRESENTATION.CALCULATED_RACE_RESULT AS DD
WHERE DD.DRIVER_NAME IN (SELECT DRIVER_NAME FROM DOMINAT_DRIVERS WHERE RANKING <=10)
GROUP BY DRIVER_NAME,DD.YEAR
ORDER BY DD.YEAR,AVG_POINTS,DD.YEAR DESC

-- COMMAND ----------


