-- Databricks notebook source
-- MAGIC %python
-- MAGIC html="<h1 align='center',>Formula <a style='color:red;''>1</a> Dominant Teams</h1>"
-- MAGIC displayHTML(html)

-- COMMAND ----------

  CREATE OR REPLACE TEMP VIEW DOMINAT_TEAM
  AS
  SELECT TEAM,
  COUNT(1) AS NO_OF_RACES,
  SUM(DC.CALCULATED_POINTS) AS TOTAL_POINTS,
  ROUND(AVG(DC.CALCULATED_POINTS),2) AS AVG_POINTS,
  RANK() OVER(ORDER BY AVG(DC.CALCULATED_POINTS) DESC ) RANKING 
  FROM f1_presentation.calculated_race_result DC
  GROUP BY TEAM
  HAVING   COUNT(1) > 100
  ORDER BY AVG_POINTS DESC

-- COMMAND ----------

  SELECT TEAM,
  DC.YEAR,
  COUNT(1) AS NO_OF_RACES,
  SUM(DC.CALCULATED_POINTS) AS TOTAL_POINTS,
  ROUND(AVG(DC.CALCULATED_POINTS),2) AS AVG_POINTS
  FROM f1_presentation.calculated_race_result DC
  WHERE TEAM IN (SELECT TEAM FROM DOMINAT_TEAM WHERE RANKING <5 )
  GROUP BY TEAM,DC.YEAR
  ORDER BY DC.YEAR,AVG_POINTS DESC

-- COMMAND ----------

 SELECT TEAM,
  DC.YEAR,
  COUNT(1) AS NO_OF_RACES,
  SUM(DC.CALCULATED_POINTS) AS TOTAL_POINTS,
  ROUND(AVG(DC.CALCULATED_POINTS),2) AS AVG_POINTS
  FROM f1_presentation.calculated_race_result DC
  WHERE TEAM IN (SELECT TEAM FROM DOMINAT_TEAM WHERE RANKING <5 )
  GROUP BY TEAM,DC.YEAR
  ORDER BY DC.YEAR,AVG_POINTS DESC

-- COMMAND ----------


